<?php
// $Id: xoops_version.php,v 1.6 2008/06/24 14:29:22 nobu Exp $
// 
$modversion =
      array('name' => _MI_SHORTCUT_NAME,
	    'version' => 0.5,
	    'description' => _MI_SHORTCUT_DESC,
	    'author' => "Nobuhiro YASUTOMI <nobuhiro.yasutomi@nifty.ne.jp>",
	    'credits' => "Nobuhiro YASUTOMI <br/>http://mysite.ddo.jp/",
	    'help' => 'help.html',
	    'license' => "modified BSD",
	    'official' => 0,
	    'image' => "shortcut_slogo.png",
	    'dirname' => "shortcut");

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'] = array("shortcut");

// OnUpdate - upgrade DATABASE 
$modversion['onUpdate'] = "onupdate.php";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Templates
$modversion['templates'][]=array('file' => 'shortcut_index.html',
				 'description' => '');
$modversion['templates'][]=array('file' => 'shortcut_register.html',
				 'description' => '');
// Blocks
$modversion['blocks'][1]=
    array('file' => "shortcut_block.php",
	  'name' => _MI_SHORTCUT_BLOCK_MENU,
	  'description' => _MI_SHORTCUT_BLOCK_MENU_DESC,
	  'show_func' => "b_shortcut_show",
	  'edit_func' => "b_shortcut_edit",
	  'options' => '',
	  'template' => 'shortcut_block_menu.html');

// Menu
$modversion['hasMain'] = 1;
?>
